# Generated by Django 2.0.9 on 2018-12-06 12:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('catalogue', '0015_auto_20181205_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('original', models.ImageField(max_length=255, upload_to='images/products/%Y/%m/', verbose_name='Original')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Hello',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Product attribute value', 'verbose_name_plural': 'Product attribute values'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='original',
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalogue.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_multi_option',
            field=models.ManyToManyField(blank=True, related_name='multi_valued_attribute_values', to='catalogue.AttributeOption', verbose_name='Value multi option'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.Product'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Image'),
            preserve_default=False,
        ),
    ]
