# Generated by Django 2.1.3 on 2018-12-07 23:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20181206_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='guitar_attributes',
        ),
        migrations.AlterField(
            model_name='product',
            name='default_attributes',
            field=wagtail.core.fields.StreamField([('attribute', wagtail.core.blocks.StructBlock([('key', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())], icon='table'))], blank=True),
        ),
    ]
